# Generated by Django 3.1.4 on 2020-12-17 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visualizador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('duracion', models.CharField(max_length=10)),
                ('no_cancion', models.IntegerField()),
                ('url', models.CharField(max_length=100)),
                ('artista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='visualizador.artista')),
            ],
        ),
        migrations.CreateModel(
            name='Musico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('instrumento', models.CharField(max_length=500)),
                ('ciudad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tablatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancion_instrumento', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('traductor', models.CharField(max_length=50)),
                ('email_traductor', models.CharField(max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='')),
                ('cancion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='visualizador.cancion')),
            ],
        ),
        migrations.CreateModel(
            name='Invitado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musico_cancion', models.CharField(max_length=50)),
                ('cancion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='visualizador.cancion')),
                ('musico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='visualizador.musico')),
            ],
        ),
        migrations.CreateModel(
            name='Integrantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artista_musico', models.CharField(max_length=50)),
                ('artista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='visualizador.artista')),
                ('musico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='visualizador.musico')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('estudio', models.CharField(max_length=50)),
                ('ano_lanzamiento', models.DateField()),
                ('no_pistas', models.IntegerField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='')),
                ('artista', models.ManyToManyField(to='visualizador.Artista')),
            ],
        ),
    ]
