# Generated by Django 3.1.4 on 2020-12-17 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualizador', '0002_album_cancion_integrantes_invitado_musico_tablatura'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Integrantes',
            new_name='Integrante',
        ),
        migrations.AlterModelOptions(
            name='cancion',
            options={'verbose_name_plural': 'Canciones'},
        ),
    ]
