# Generated by Django 3.1.4 on 2020-12-17 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visualizador', '0003_auto_20201217_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancion',
            name='album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='visualizador.album'),
        ),
    ]
