# Generated by Django 3.1.4 on 2020-12-17 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualizador', '0004_cancion_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancion',
            name='artista',
        ),
    ]
