# Generated by Django 3.1.4 on 2021-01-26 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visualizador', '0005_remove_cancion_artista'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitado',
            name='musico_cancion',
        ),
        migrations.AddField(
            model_name='musico',
            name='artista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='visualizador.artista'),
        ),
        migrations.DeleteModel(
            name='Integrante',
        ),
    ]
