# Generated by Django 3.1.4 on 2021-01-26 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualizador', '0007_auto_20210126_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cancion',
            old_name='invitado',
            new_name='musico',
        ),
    ]
