# Generated by Django 3.1.4 on 2021-01-26 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visualizador', '0008_auto_20210126_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancion',
            name='artista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='visualizador.artista'),
        ),
    ]
