# Generated by Django 3.1.4 on 2021-01-26 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visualizador', '0009_cancion_artista'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artista',
        ),
        migrations.AddField(
            model_name='album',
            name='artista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='visualizador.artista'),
        ),
    ]
