# Generated by Django 3.1.4 on 2021-01-26 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualizador', '0011_auto_20210126_1705'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invitado',
        ),
    ]
