# Generated by Django 3.1.4 on 2021-01-27 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visualizador', '0014_auto_20210126_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancion',
            name='musico',
        ),
        migrations.CreateModel(
            name='Invitado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musico_cancion', models.CharField(max_length=50)),
                ('cancion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='visualizador.cancion')),
                ('musico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='visualizador.musico')),
            ],
        ),
    ]
